# 项目相关配置
platform:
  # 日志地址
  logPath: ./logs
  # 系统版本
  version: 1.0.0
  # 端口
  port: 8888
  # 秘钥
  secret: YTY9FRenXiJNeE2x

# MQ配置
rocketmq:
  # 服务接入地址
  name-server: 110.42.56.25:9876
  # 消费者配置
  consumer:
    # AccessKey
    access-key: admin123
    # SecretKey
    secret-key: admin123admin123
  # 消费主题
  topic: testim
  # 消费者组
  group: testim